---
- name: Configure a appsvcs iapp service using parameters in JSON document
  bigip_iapp_service:
    name: "{{app_name}}"
    user: "{{ username }}"
    password: "{{ password }}"
    server: "{{ inventory_hostname }}"
    template: "{{ f5template }}"
    validate_certs: "false"
    state: "{{ state }}"
    parameters: "{{ lookup('file', '{{ app_name }}_autogen.json') }}" 
  delegate_to: localhost
...
