---
- include: bigip_license/license.yml 
  vars:
    - key: "G0759-89928-41864-66754-5574207"

- include: bigip_vlan/add_untagged_vlan.yml 
  vars:
    - name: "external" 
    - untagged_interface: "1.1"

- include: bigip_selfip/add_selfip.yml 
  vars:
    - name: "ext_self_v4" 
    - address: "{{ ext_self_ip }}" 
    - netmask: "{{ ext_netmask }}"
    - vlan_name: "external" 
    - route_domain: "0" 
    - traffic_group: "traffic-group-local-only"

- include: bigip_selfip/add_selfip_master.yml
  vars:
    - name: "ext_self_floating_v4"
    - address: "{{ ext_floating_self_ip }}"
    - netmask: "{{ ext_netmask }}"
    - vlan_name: "external"
    - route_domain: "0"
    - traffic_group: "traffic-group-1"

- include: bigip_vlan/add_untagged_vlan.yml 
  vars: 
    - name: "internal" 
    - untagged_interface: "1.2"

- include: bigip_selfip/add_selfip.yml 
  vars:
    - name: "int_self_v4" 
    - address: "{{ int_self_ip }}" 
    - netmask: "{{ int_netmask }}" 
    - vlan_name: "internal" 
    - route_domain: "0" 
    - traffic_group: "traffic-group-local-only"

- include: bigip_selfip/add_selfip_master.yml
  vars:
    - name: "int_self_floating_v4"
    - address: "{{ int_floating_self_ip }}"
    - netmask: "{{ int_netmask }}"
    - vlan_name: "internal"
    - route_domain: "0"
    - traffic_group: "traffic-group-1"

- include: bigip_vlan/add_untagged_vlan.yml
  vars:
    - name: "ha"
    - untagged_interface: "1.3"

- include: bigip_selfip/add_selfip.yml
  vars:
    - name: "ha_self_v4"
    - address: "{{ ha_self_ip }}"
    - netmask: "{{ ha_netmask }}"
    - vlan_name: "ha"
    - route_domain: "0"
    - traffic_group: "traffic-group-local-only"


- include: bigip_device_ntp/set_ntp_server.yml 
  vars: 
    - ntp_server1: "0.de.pool.ntp.org" 
    - ntp_server2: "1.de.pool.ntp.org"

- include: bigip_device_ntp/set_timezone.yml 
  vars:
    - timezone: "Europe/Berlin"

##bug - https://github.com/mcgonagle/ansible_f5/issues/22
- include: bigip_hostname/set_hostname.yml
#- include: bigip_hostname/set_hostname.yml hostname="bigip.demo.local"

# Issue dhcp needs to be disabled - https://github.com/mcgonagle/ansible_f5/issues/10
- include: bigip_device_dns/set_dns.yml name_server1="10.128.10.2" name_server2="8.8.4.4" search_domain1="localdomain" search_domain2="lab.local" 

##bug -https://github.com/mcgonagle/ansible_f5/issues/11
##- include: bigip_remote_syslog/set_syslog_server.yml remote_host="10.10.10.10" remote_port="514" local_ip="10.0.1.120"

- include: bigip_user/add_user.yml 
  vars:
    - username_credential: "ralf" 
    - password_credential: "{{ ralf_password }}" 
    - full_name: "ralf Bruenig" 
    - partition_access: "all:admin" 
    - update_password: "on_create"

- include: bigip_user/add_user.yml 
  vars: 
    - username_credential: "bob" 
    - password_credential: "{{ bob_password }}" 
    - full_name: "Bob Bob" 
    - partition_access: "Common:operator" 
    - update_password: "on_create"

- include: bigip_provision/provision_module.yml module="asm" level="nominal"
- include: bigip_provision/provision_module.yml module="afm" level="nominal"
- include: bigip_provision/provision_module.yml module="avr" level="nominal"


- include: bigip_ssl_certificate/import_certificate.yml

- include: bigip_command/set_gui_idle-timeout.yml
  vars:
    - gui_idle_timeout: 7200

- include: bigip_sys_db/set_records-per-screen.yml
  vars:
    - records_per_screen: 100

- include: bigip_sys_global/set_gui_setup.yml


##########
# HA Setup

- include: bigip_command/set_configsync_address.yml
  vars:
    - address: "{{ int_self_ip }}"

- include: bigip_command/set_heartbeat_address.yml
  vars:
    - address: "{{ ha_self_ip }}"
    - mgmt_address: "{{ mgmt_ip }}"

- include: bigip_command/set_mirroring_address.yml
  vars:
    - address: "{{ int_self_ip }}"

- include: bigip_command/set_device_trust.yml

- include: bigip_command/create_device_group.yml

- include: bigip_command/initial_config_sync.yml

- include: bigip_command/initial_config_sync.yml
  vars:
    - device_group_name: "datasync-global-dg"

- include: bigip_command/check_sync_status.yml

- include: bigip_command/check_ha_status.yml

# HA setup - end
################
...
