---
- name: Set records per screen to {{ records_per_screen }}
  bigip_sys_db:
    key: "ui.system.preferences.recordsperscreen"
    value: "{{ records_per_screen }}"
    provider: "{{ provider }}"
  delegate_to: localhost
...
