---
- name: Set the DNS settings 
  bigip_device_dns:
    name_servers:
        - "{{ name_server1 }}"
        - "{{ name_server2 }}"
    search:
        - "{{ search_domain1 }}"
        - "{{ search_domain2 }}"
    ip_version: "4"
    provider: "{{ provider }}"
  delegate_to: localhost
...
