---
- name: Add remote syslog server
  bigip_remote_syslog:
    remote_host: "{{ remote_host }}" 
    remote_port: "{{ remote_port }}" 
    local_ip: "{{ local_ip }}"
    provider: "{{ provider }}"
  delegate_to: localhost
...
