---
#############################
# Add/Remove iApp templates #
#############################

- name: Deploy iApp template {{ f5template }}.tmpl
  bigip_iapp_template:
    content: "{{ lookup('file', '{{ f5template }}.tmpl') }}"
    state: "{{ state }}"
    provider: "{{ provider }}"
  delegate_to: localhost

...
