---
- name: Manage the iRule contained in the static file bodgeit-rewrite.tcl to the LTM module
  bigip_irule:
    name: "OutOfService_Response"
    module: "ltm"
    content: "{{ lookup('file', 'irules/apology_page.tcl') }}"
    partition: "{{ partition }}"
    provider: "{{ provider }}"
    state: "{{ state }}"
  delegate_to: localhost
...
