---
##############################################
# Add/Remove Application Service over BIG-IQ #
##############################################

- name: get auth token
  uri:
    url: https://{{ inventory_hostname }}/mgmt/shared/authn/login
    method: POST
    user: "{{ username }}"
    password: "{{ password }}"
    body: "{
              \"username\":\"{{username}}\",
              \"password\":\"{{password}}\",
              \"loginProviderName\": \"local\"
      }"
    force_basic_auth: yes
    status_code: 200
    body_format: json
    validate_certs: no
  register: auth
  delegate_to: localhost

# Add Application Service
#########################
- name: Deploy Application {{ j2template }} - {{ app_name }}
  uri:
    url: https://{{ inventory_hostname }}/mgmt/cm/global/tasks/apply-template
    method: POST
    headers:
      X-F5-Auth-Token: "{{auth.json.token.token}}"
    body: "{{ lookup('template', '{{ j2template }}.j2') }}"
    force_basic_auth: no
    status_code: 200,202
    body_format: json
    validate_certs: no
  delegate_to: localhost
  when: status == "present"

# Remove Application Service


- name: Get virtual list
  uri:
    url: "https://{{ inventory_hostname }}/mgmt/shared/index/config?$filter=kind eq 'cm:adc-core:working-config:ltm:virtual:adcvirtualstate' and tags/namevalue eq 'BIGIQ_configSetName : {{ app_name }}'"
    #url: https://{{ inventory_hostname }}/mgmt/shared/index/config?$filter=kind eq 'cm:adc-core:working-config:ltm:virtual:adcvirtualstate'
    method: GET
    headers:
      X-F5-Auth-Token: "{{auth.json.token.token}}"
    force_basic_auth: no
    status_code: 200
    body_format: json
    validate_certs: no
  register: virtualList
  delegate_to: localhost
  when: status == "absent"


- name: Delete all virtuals of {{ app_name }}
  uri:
    url: "https://{{ inventory_hostname }}{{ item.selfLink.split('localhost')[1] }}"
    method: DELETE
    headers:
      X-F5-Auth-Token: "{{auth.json.token.token}}"
    force_basic_auth: no
    status_code: 200
    body_format: json
    validate_certs: no
  delegate_to: localhost
  when: status == "absent"
  with_items: "{{ virtualList.json['items'] }}"


- name: Get pool list
  uri:
    url: "https://{{ inventory_hostname }}/mgmt/shared/index/config?$filter=kind eq 'cm:adc-core:working-config:ltm:pool:adcpoolstate' and tags/namevalue eq 'BIGIQ_configSetName : {{ app_name }}'"
    method: GET
    headers:
      X-F5-Auth-Token: "{{auth.json.token.token}}"
    force_basic_auth: no
    status_code: 200
    body_format: json
    validate_certs: no
  register: poolList
  delegate_to: localhost
  when: status == "absent"

- name: Delete all pools of {{ app_name }}
  uri:
    url: "https://{{ inventory_hostname }}{{ item.selfLink.split('localhost')[1] }}"
    method: DELETE
    headers:
      X-F5-Auth-Token: "{{auth.json.token.token}}"
    force_basic_auth: no
    status_code: 200
    body_format: json
    validate_certs: no
  delegate_to: localhost
  when: status == "absent"
  with_items: "{{ poolList.json['items'] }}"


- name: Get node list
  uri:
    url: "https://{{ inventory_hostname }}/mgmt/shared/index/config?$filter=kind eq 'cm:adc-core:working-config:ltm:node:adcnodestate' and tags/namevalue eq 'BIGIQ_configSetName : {{ app_name }}'"
    method: GET
    headers:
      X-F5-Auth-Token: "{{auth.json.token.token}}"
    force_basic_auth: no
    status_code: 200
    body_format: json
    validate_certs: no
  register: nodeList
  delegate_to: localhost
  when: status == "absent"

- name: Delete all pools of {{ app_name }}
  uri:
    url: "https://{{ inventory_hostname }}{{ item.selfLink.split('localhost')[1] }}"
    method: DELETE
    headers:
      X-F5-Auth-Token: "{{auth.json.token.token}}"
    force_basic_auth: no
    status_code: 200
    body_format: json
    validate_certs: no
  delegate_to: localhost
  when: status == "absent"
  with_items: "{{ nodeList.json['items'] }}"



- name: Get Application ID of {{ app_name }}
  uri:
    url: https://{{ inventory_hostname }}/mgmt/cm//global/config-sets?$filter=configSetName eq '{{ app_name }}'
    method: GET
    headers:
      X-F5-Auth-Token: "{{auth.json.token.token}}"
    force_basic_auth: no
    status_code: 200
    body_format: json
    validate_certs: no
  register: appList
  delegate_to: localhost
  when: status == "absent"

- debug:
    msg:
    - "totalItems: {{ appList.json['totalItems'] }}"
    - "id: {{ appList.json['items'][0].id }}"
  when: status == "absentt"

- name: Delete Application {{ app_name }}
  uri:
    url: https://{{ inventory_hostname }}/mgmt/cm//global/config-sets/{{ appList.json['items'][0].id }}
    method: DELETE
    headers:
      X-F5-Auth-Token: "{{auth.json.token.token}}"
    force_basic_auth: no
    status_code: 200
    body_format: json
    validate_certs: no
  register: appList
  delegate_to: localhost
  when: status == "absent"


...
