---
- name: Deploy iApp template {{ f5template }}.tmpl
  bigip_iapp_template:
    user: "{{username}}"
    password: "{{password}}"
    server: "{{ inventory_hostname }}"
    content: "{{ lookup('file', '{{ f5template }}.tmpl') }}"
    state: "{{ state }}"
  delegate_to: localhost
...
