---
- name: Add the user "{{ username_credential }}"
  bigip_user:
    username_credential: "{{ username_credential }}"
    password_credential: "{{ password_credential }}"
    full_name: "{{ full_name }}"
    partition_access: "{{ partition_access }}"
    update_password: "{{ update_password }}"
    state: "present"
    provider: "{{ provider }}"
  delegate_to: localhost
...
