---
- name: Perform initial sync of device-group {{ device_group_name }}
  bigip_command:
    user: "{{ username }}"
    password: "{{ password }}"
    server: "{{ inventory_hostname }}"
    commands:
      - run cm config-sync force-full-load-push to-group {{ device_group_name }}
  when: inventory_hostname in groups['master']
  delegate_to: localhost
...
