---
# Target is Ansible v2.5
#- import_tasks: bigip_license/license.yml 
#  vars:
#    - key: "{{ license_key }}"


- name: Add VLANs
  bigip_vlan:
    name: "{{ item.name }}"
    tag: "{{ item.tag }}"
    #tagged_interfaces: "{{ item.interfaces.tagged }}"
    untagged_interfaces: "{{ item.interfaces.untagged }}"
    provider: "{{ provider }}"
  loop: "{{ vlans }}"
  delegate_to: localhost

- name: Add HA Self-IPs
  bigip_selfip:
    name: "{{ item.name }}"
    address: "{{ item.address }}"
    netmask: "{{ item.netmask }}"
    vlan: "{{ item.vlan }}"
    provider: "{{ provider }}"
  loop: "{{ self_ips }}"
  delegate_to: localhost

- name: Configure hostname
  bigip_hostname:
    hostname: "{{ hostname }}"
    provider: "{{ provider }}"
  delegate_to: localhost

- import_tasks: bigip_device_ntp/set_ntp_server.yml 
  vars: 
    - ntp_server1: "0.de.pool.ntp.org" 
    - ntp_server2: "1.de.pool.ntp.org"

- import_tasks: bigip_device_ntp/set_timezone.yml 
  vars:
    - timezone: "Europe/Berlin"

# Issue dhcp needs to be disabled - https://github.com/mcgonagle/ansible_f5/issues/10
- import_tasks: bigip_device_dns/set_dns.yml
  vars:
    - name_server1: "10.128.10.2"
    - name_server2: "8.8.4.4"
    - search_domain1: "localdomain"
    - search_domain2: "lab.local" 

#- import_tasks: bigip_user/add_user.yml 
#  vars:
#    - username_credential: "ralf" 
#    - password_credential: "{{ ralf_password }}" 
#    - full_name: "ralf Bruenig" 
#    - partition_access: "all:admin" 
#    - update_password: "on_create"

#- import_tasks: bigip_user/add_user.yml 
#  vars: 
#    - username_credential: "bob" 
#    - password_credential: "{{ bob_password }}" 
#    - full_name: "Bob Bob" 
#    - partition_access: "Common:operator" 
#    - update_password: "on_create"

#- import_tasks: bigip_provision/provision_module.yml module="asm" level="nominal"
#- import_tasks: bigip_provision/provision_module.yml module="afm" level="nominal"
#- import_tasks: bigip_provision/provision_module.yml module="avr" level="nominal"

#- import_tasks: bigip_ssl_certificate/import_certificate.yml

- import_tasks: bigip_command/set_gui_idle-timeout.yml
  vars:
    - gui_idle_timeout: 7200

- import_tasks: bigip_sys_db/set_records-per-screen.yml
  vars:
    - records_per_screen: 100

- import_tasks: bigip_sys_global/set_gui_setup.yml

...
