---
- name: Manage a VIP
  bigip_virtual_server:
    description: "{{ description }}"
    destination: "{{ destination }}"
    name: "{{ name }}"
    pool: "{{ pool }}"
    port: "{{ port }}"
    snat: "{{ snat }}"
    all_profiles:
      - "{{ all_profiles }}"
    all_rules:
      - "{{ all_rules }}"
    partition: "{{ partition }}"
    provider: "{{ provider }}"
    state: "{{ state }}"
  delegate_to: localhost
...
