---
- name: Manage a pool
  bigip_pool:
    name: "{{ name }}"
    partition: "{{ partition }}"
    provider: "{{ provider }}"
    state: "{{ state }}"
    monitors:
      - "{{ monitor }}"
    monitor_type: "and_list"
  delegate_to: localhost
...
