---
##############################################
# Add/Remove Application Service Deploaments #
##############################################

- name: Configure a appsvcs iapp service using parameters in JSON document
  bigip_iapp_service:
    name: "{{app_name}}"
    partition: "{{ partition }}"
    template: "{{ f5template }}"
    state: "{{ state }}"
    parameters: "{{ lookup('template', '{{ j2template }}.j2') }}"
    provider: "{{ provider }}"
  delegate_to: localhost
...
