---
- name: Check guest status 
  bigip_command:
    user: "{{ username }}"
    password: "{{ password }}"
    server: "{{ vcmp_host }}"
    commands:
      - show vcmp guest {{ vcmp_guest_name }}
    wait_for:
      - result[0] contains "running"
    match: all
    interval: 5
    retries: 120
    validate_certs: "no"
  delegate_to: localhost

# Even with 10 seconds I run into issues, so I increased it to 20
#- name: Delay for 20 seconds
#  pause:
#    seconds: 20
...
