---
#############
#Add objects#
#############
- import_tasks: bigip_node/add_node.yml 
  vars: 
    - host: "10.10.10.208" 
    - name: "member08" 
    - monitor: "/Common/icmp"
  when: state == "present"

- import_tasks: bigip_pool/manage_pool.yml 
  vars: 
    - name: "pool20"
    - monitor: "/Common/http_head_f5"
  when: state == "present"

- import_tasks: bigip_pool_member/manage_members.yml 
  vars: 
    - host: "/{{ partition }}/member08" 
    - pool: "/{{ partition }}/pool20"
    - port: "80"
  when: state == "present"

- import_tasks: bigip_irule/manage_irule.yml
  when: state == "present"

- import_tasks: bigip_monitor_tcp/manage_tcp_monitor.yml
  when: state == "present"

- import_tasks: bigip_monitor_http/manage_http_monitor.yml
  when: state == "present"

- import_tasks: bigip_virtual_server/manage_vip.yml 
  vars:
    - description: "foo-vip" 
    - destination: "10.128.10.20" 
    - name: "vip20" 
    - pool: "/{{ partition }}/pool20" 
    - port: "80" 
    - snat: "Automap"
    - all_profiles: "/Common/http"
    - all_rules: "/{{ partition }}/OutOfService_Response"
  when: state == "present"

################
#Remove objects#
################
- import_tasks: bigip_virtual_server/manage_vip.yml
  vars:
    - description: "foo-vip" 
    - destination: "10.128.10.20" 
    - name: "vip20" 
    - pool: "/{{ partition }}/pool20" 
    - port: "80" 
    - snat: "Automap"
    - all_profiles: "/Common/http"
    - all_rules: "/{{ partition }}//OutOfService_Response"
  when: state == "absent"

- import_tasks: bigip_irule/manage_irule.yml
  when: state == "absent"

- import_tasks: bigip_monitor_tcp/manage_tcp_monitor.yml
  when: state == "absent"

- import_tasks: bigip_monitor_http/manage_http_monitor.yml
  when: state == "absent"

- import_tasks: bigip_pool/manage_pool.yml 
  vars: 
    - name: "pool20" 
    - monitor: "/Common/http_head_f5"
  when: state == "absent"

- import_tasks: bigip_node/remove_node.yml 
  vars:
    - host: "10.10.10.208"
    - name: "member08" 
  when: state == "absent"
...
