---
- name: Import PEM Certificate from local disk
  bigip_ssl_certificate:
    name: "domain"
    cert_content: "{{ lookup('file', 'domain.crt') }}"
    key_content: "{{ lookup('file', 'domain.key') }}"
    state: "present"
    provider: "{{ provider }}"
  delegate_to: localhost
...
