---
- name: Manage members in a pool
  bigip_pool_member:
    provider: "{{ provider }}"
    user: "{{ username }}"
    password: "{{ password }}"
    server: "{{ inventory_hostname }}"
    host: "{{ host }}"
    pool: "{{ pool }}"
    port: "{{ port }}"
    partition: "{{ partition }}"
    state: "{{ state }}"
  delegate_to: localhost
...
