# Collect all playbooks
#- import_playbook: onboarding.yml
- import_playbook: operations.yml

## iApp part:
- import_playbook: iAppTemplate.yml
  when: state == "present"

- import_playbook: http_iApp.yml
- import_playbook: https_waf_iApp.yml
- import_playbook: scp_iApp.yml

- import_playbook: iAppTemplate.yml
  when: state == "absent"

