#####################################################
# Deployment wit the default HTTPS offload template #
#####################################################
#
---
  - hosts: "{{ target }}"
    gather_facts: False
    roles:
      - DO
    vars:
      ansible_ssh_user: "{{ username }}"
      ansible_ssh_pass: "{{ password }}"
      DOrpm: f5-declarative-onboarding-1.2.0-3.noarch.rpm
      AS3rpm: f5-appsvcs-3.8.1-1.noarch.rpm
      provider:
        server: "{{ inventory_hostname }}"
        server_port: "443"
        user: "{{ username }}"
        password: "{{ password }}"
        validate_certs: "no"

...
