###############################################################
# https deployment with optimizations and LAMP WAF protection #
###############################################################
#
# network:
# - SNAT
# - TCP full proxy
# - increased tcp buffer for larger packages
#
# http feature:
# - X-forwarded-For header
# - http static caching
# - Internal connection reuse
# - port 80 redirect
# 
# WAF:
# - Blacklisting for LAMP
# - Log all requests


---
  - hosts: bigip
    gather_facts: False
    roles:
      - iApps
    vars:
      - app_name: "f5_app"
      - monitor_request_path: "/f5/index.php"
      - monitor_response: "Welcome"
      - vip: "10.128.10.25" 
      - members:
        -
          ip: "10.10.10.211"
          port: "80"
        -
          ip: "10.10.10.212"
          port: "80"
        -
          ip: "10.10.10.213"
          port: "80"

## don't touch: ##
      - f5template: "appsvcs_integration_v2.0.004_waf"
      - j2template: "appsvce_https_waf"

...
