---
  - hosts: bigip
    gather_facts: False
    roles:
      - iApps
    vars:
      - app_name: "http_app_22"
      - vip: "10.128.10.22" 
      - members:
        -
          ip: "10.10.10.211"
          port: "80"
        -
          ip: "10.10.10.212"
          port: "80"

## don't touch: ##
      - f5template: "appsvcs_integration_v2.0.004_waf"
      - j2template: "appsvce_http"

...
