---
- hosts: "{{ target }}"
  gather_facts: False
  roles:
    - onboarding 

  vars:
    partition: "Common"
    provider:
      server: "{{ inventory_hostname }}"
      server_port: "443"
      user: "{{ username }}"
      password: "{{ password }}"
      validate_certs: "no"

...
