- name: Deploy application on BIG-IQ
  hosts: "{{ target }}"
  gather_facts: false
  vars:
    username: "admin"
    password: "admin"
    gui_idle_timeout: "3600"
    record_per_screen: "100"

  tasks:

  - name: set GUI_idle_timeout to {{ gui_idle_timeout}} and records_per_screen to {{ record_per_screen }}
    bigip_command:
      user: "{{ username }}"
      password: "{{ password }}"
      server: "{{ inventory_hostname }}"
      commands:
      - modify sys httpd auth-pam-idle-timeout {{ gui_idle_timeout }}
      - modify /sys db ui.system.preferences.recordsperscreen value {{ record_per_screen }}
    delegate_to: localhost
    
