---
- name: Manage the TCP Monitor
  bigip_monitor_tcp:
    name: "my_tcp_monitor"
    parent: "/Common/tcp"
    send: ""
    receive: ""
    partition: "{{ partition }}"
    provider: "{{ provider }}"
    state: "{{ state }}"
  delegate_to: localhost
...
