---
- name: Manage the HTTP Monitor
  bigip_monitor_http:
    name: "my_http_monitor"
    send: "GET /\r\n"
    receive: ""
    partition: "{{ partition }}"
    provider: "{{ provider }}"
    state: "{{ state }}"
  delegate_to: localhost
...
