---
- name: Add a new node
  bigip_node:
    provider: "{{ provider }}"
    host: "{{ host }}"
    name: "{{ name }}"
    partition: "{{ partition }}"
    state: "{{ state }}"
    monitors:
      - "{{ monitor }}"
  delegate_to: localhost
...
